services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
